[package]
name = "sorridi_xyz"
version = "1.0.0"
authors = ["Sorridi <reallygud@protonmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
tokio = "1.4.0"
rocket = "0.4.7"
derive-getters = "0.2.0"
